### ISSUE TITLE
Switch to use coincurve

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-evm#10]
### What is wrong

The library currently uses it's own functions for ECDSA signing and verification.

* This is slow.
* This is bad crypto.

### How can it be fixed.

Switch to use the coincurve library.

https://pypi.python.org/pypi/coincurve/4.4.1

**Comment by pckilgore** [comment]
See also: 
- ethereum/pyethereum#713
- raiden-network/raiden#534

**Comment by pipermerriam** [comment]
After a recent conversation, I'm thinking that we may keep the local python implementation for a bit longer and implement a pluggable ECC backend system that allows for swapping in different implementations.  The reasoning behind this is to eliminate any need for system level dependencies which coincurve as a hard dependency would introduce.

**Comment by ofek** [comment]
@pipermerriam Author of https://github.com/ofek/coincurve here. Just fyi a binary wheel is available for every distribution so there are no system level dependencies. Just add coincurve to `install_requires`.
