### ISSUE TITLE
Need a Chain that syncs only block headers

### ISSUE THREAD

**Issue by gsalgado** [pipermerriam/py-evm#113]
The existing Chain implementation assumes a synced database with all blocks/headers/state is available, but for the light client we'll need one that only syncs only block headers and fetches any extra data (blocks/receipts/contract-code/proofs) on demand.

**Comment by pipermerriam** [comment]
So I've been thinking about something independently that *may* be a good fit for this.

What about a *backend* system for all of the functions that are used for retrieving and persisting chain data (blocks/headers/transactions/receipts).

```
class BaseChainDB:
    def get_block_by_hash(self, block_hash):
        pass

    def get_block_by_canonical_block_number(self, block_number):
        pass

    def persist_block(self, block):
        pass

    ...  # more methods for the other objects....
```

Benefits I see...

* Moves logic out of the `Chain` class, making it a bit more of a *pure* interface
* Allows for full client and light client `Chain` instances to use different strategies for retrieval of these objects.

In general, it seems like a healthy abstraction, thoughts?

**Comment by gsalgado** [comment]
I think that makes sense, so I went ahead and tried it at #114. Notice that moving get_transactions_from_db() to BaseChainDB would require some work, I think, but it's not really needed, so we might as well leave it out for now. What do you think?

**Comment by pipermerriam** [comment]
I'm thinking that we want to move *all* db access to be inside this class.  I noted this in the other PR but that would include moving the `VM.state_db` API onto the `ChainDB` class.

This would enable things like *fancy* chain databases that pull information not available by the LES protocol over some alternative API (like infura or etherscan).

**Comment by gsalgado** [comment]
We now have a `BaseChainDB` and `LightChain`
