### ISSUE TITLE
Some BaseChainDB methods may leave the database in an inconsistent state. 

### ISSUE THREAD

**Issue by gsalgado** [pipermerriam/py-evm#135]
For instance, `persist_header_to_db()` stores the header in the DB, calculates the total difficulty for that block and then stores that in the DB as well, but it can crash when calculating the difficulty and in that case we'd end up with the header stored but without its total difficulty. 

There are a few ways to address that:

1. Use a database that supports ACID transactions
2. Batch DB updates and apply them atomically
3. Deal with it manually, with a bare except that rolls back updates

Number 1) is problematic because LevelDB does not support transactions, 3) is error prone and tedious, so I think 2) is our best option, but it means we need to add support for that to `MemoryDB` as well.

**Comment by pipermerriam** [comment]
What about a wrapper that works for any KV store that I'll refer to as `AtomicDB` until a better name surfaces.  It would present the following API

```python
with AtomicDB(db) as atomic_db:
    atomic_db[b'a'] = b'arst'  # doesn't write the key to the database but rather to a local cache.
    assert atomic_db[b'a'] == b'arst'  # intelligently returns the value from the cache
    atomic_db[b'b'] = b'tsra'  
# upon exiting the context, it writes all of the keys from the cache into the underlying database.
```

In the case of an exception within the context block, no change would occur to the underlying database.  We could also implement an alternate API something like the following.

```python
atomic_db = AtomicDB(db)
transaction = atomic_db.transaction()
transaction[b'a'] = b'arst'
transaction[b'b'] = b'tsra'

transaction.commit()  # writes all the changes.
```

Seems simple enough and I think it fits loosely into option 2.

**Comment by gsalgado** [comment]
That is a nice API indeed. We'd still need the underlying KV stores to support batch updates, though, or else in our batch.commit() implementation we'd need to implement a rollback mechanism ourselves, in case anything fails while we're performing any of the updates

**Comment by pipermerriam** [comment]
I specified this in a separate ticket: https://github.com/pipermerriam/py-evm/issues/160
