### ISSUE TITLE
Block and Header validation

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-evm#16]
The full validation rules from the yellow paper need to be added for blocks and headers.  Convention thus far for validation is as follows.

1. Validation or RLP objects is separated into local validation and evm aware validation.
    - local validation entails things that can be validated from within the context of the object such as making sure that all fields are of the correct type and within the established ranges.
    - evm aware validation is for everything else, such as checking that a transaction's nonce is greater than the current nonce from the evm state.
2. Local validation is done as a method on the object itself `RLPObject.validate()`
3. EVM aware validation is done as a method on the `VM` class.  Typically the default implementation should throw a `NotImplementedError` and the *real* validation logic should be setup only for the mainnet VM classes.

The block and header validation rules should be pulled from the yellow paper: https://ethereum.github.io/yellowpaper/

In short they are:

* All fields on the `BlockHeader` are of the appropriate type and within range.
* All fields on the `Block` are of the appropriate type and within range.
* `BlockHeader.state_root` exists within the `db` (evm aware)
* `BlockHeader.uncles_hash` is equal to the rlp encoded list of uncles from the block (local)
* `BlockHeader.transactions_hash` is equal to the root hash of the `Block.transaction_db`. (local)
* `BlockHeader.receipts_hash` is equal to the root hash of the `Block.receipts_db`. (local)
* `BlockHeader.bloom` is equal to the bloom filter containing all of the *bloomables* from all of the logs from all of the receipts in the block. (local)
* `BlockHeader.difficulty` matches the expected difficulty computed from the timestamp of the previous header. (evm aware)
* `BlockHeader.gas_limit` is within the allowed range. (evm aware)
* `BlockHeader.gas_used` is less-than-or-equal to the `BlockHeader.gas_limit` (local)
* `BlockHeader.nonce` and `BlockHeader.mix_hash` satisfy the proof of work rules (evm aware due to DAG)
* `BlockHeader.timestamp` is greater-than the parent header timestamp. (local)
* `BlockHeader.block_number` is equal-to the parent block number + 1
* `BlockHeader.extra_data` is less-than-or-equal to 32 bytes in length.

**Comment by gsalgado** [comment]
With https://github.com/pipermerriam/py-evm/commit/3516d196cdbad4ef14af0de3198be26d21018f97 I believe all of those checks are in place now
