### ISSUE TITLE
Enable and fix remaining Transaction Tests

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-evm#32]
https://github.com/pipermerriam/py-evm/blob/master/tests/json-fixtures/test_transactions.py#L44

```python
def transaction_fixture_skip_fn(fixture_path, fixture_name, fixture):
    # TODO: enable all fixture tests
    return "ttTransactionTest.json" not in fixture_path
```

Removing this line from `tests/json-fixtures/test_transactions.py` will enable about 150 transaction tests that are currently being skipped.  These should be enabled and fixed if they are failing.

**Comment by djrtwo** [comment]
Looking for an entry point into this project. This seems like a good place, right?

**Comment by pipermerriam** [comment]
Yes, this is open and up for grabs.
