### ISSUE TITLE
Unit tests for the `GasMeter` object

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-evm#49]
### What is wrong?

No unit tests for the `evm.vm.gas_meter.GasMeter` object.

### How can it be fixed

Write some unit tests to validate:

- It correctly validates the `start_gas` parameter during instantiation.
- It doesn't allow negative values in `consume_gas()`, `return_gas()` and `refund_gas()`
- it throws an `OutOfGas` exceptions if `consume_gas()` is called with an amount larger than the remaining gas.
- It tracks consumption, returning, and refunding gas correctly (this can be a simple procedural test)

**Comment by njgheorghita** [comment]
![giphy-downsized-large 1](https://user-images.githubusercontent.com/9753150/28746045-f3ad770c-7441-11e7-80c2-ec0a8754da75.gif)
