### ISSUE TITLE
Unit tests for the `CodeStream` object

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-evm#50]
### What is wrong?

There are no tests for the `evm.vm.code_stream.CodeStream` object.

### How can it be fixed

Write unit tests that test:

- Ensure the object only accepts `bytes` types during instantiation.
- `v.peek()` correctly returns the next opcode without changing the location in the code stream.
- `v.next()` and `next(v)` return the correct next opcode.
- When the end of the bytecode is reached, it returns the `STOP` opcode.
- Use of the context manager functionality `with v.seek(position)` correctly reverts to the original stream position when the context exits.
- `v.is_valid_opcode()` correctly determines that bytes after a `PUSHXX` operation are not valid.

**Comment by njgheorghita** [comment]
![giphy 10](https://user-images.githubusercontent.com/9753150/28940236-3dc6d726-7851-11e7-80a9-f1f816acb490.gif)
