### ISSUE TITLE
Unit tests for the `Memory` object

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-evm#51]
### What is wrong?

There are no unit tests for the functionality of the `evm.vm.memory.Memory` object

### How can it be fixed

Write unit tests to verify that it:

- `write(..)` function parameters are validated:
  - `start_position` and `size` are valid 256 bit unsigned integers.
  - `value` is of type bytes
  - The length of `value` is the same as `size` (this may actually not be required by the EVM).
  - Invalid to write a value that would extend beyond the end of the total memory size.
- `extend` appropriately extends the memory, only padding with zeros when the size increases.
- `read` pulls the correct bytes from memory.

**Comment by njgheorghita** [comment]
![giphy 8](https://user-images.githubusercontent.com/9753150/28886523-0cd3924c-7777-11e7-88be-40828335b063.gif)
