### ISSUE TITLE
Write unit tests for the `Stack` object

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-evm#52]
### What is wrong?

The `evm.vm.stack.Stack` object does not have any unit tests.

### How can it be fixed

Write unit tests to verify that it:

- `push` validates that the value being pushed on is a valid stack item.
- `push` and `dup` do not allow the stack to exceed 1024 items.
- `pop` returns the latest stack item (or throws if the stack is empty)
- the value returned from `pop` is cast to the appropriate type as specified by `type_hint`
- `swap` and `dup` perform the correct shuffling and duplication of the correct stack items.
- `pop`, `swap`, and `dup` raise `InsufficientStack` when the stack does not contain enough items.

**Comment by njgheorghita** [comment]
![giphy 6](https://user-images.githubusercontent.com/9753150/28828911-6ae2fa6e-768f-11e7-9288-7f0fd835496f.gif)
