### ISSUE TITLE
Write unit tests for the `Message` object

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-evm#53]
### What is wrong?

There are no unit tests for the `Message` object

### How can it be fixed

Write unit tests that verify that it:

- all `__init__` parameters are properly validated.
- `v.is_origin` correctly returns `True/False` for whether this message is the *origin* message meaning that it's the ourtermost VM message being executed.
- `v.origin` property returns correct value.
- `v.code_address` returns correct value when `to` address is set to `CREATE_CONTRACT_ADDRESS`.
- `v.storage_address` returns correct value when message is performaing contract creation.
- `v.is_create` returns `True` when message is for contract creation.

**Comment by egong** [comment]
@pipermerriam giving this one a shot.
