### ISSUE TITLE
Write unit test for the `Computation` object

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-evm#54]
### What is wrong?

There are no unit test for the `evm.vm.computation.Computation` object

### How can it be fixed

Write unit tests to verify that it:

- Basic smoke tests for `prepare_child_message`.  Check depth is increased, origin is preserved, etc.
- `expand_memory` extension correctly validates parameters and charges appropriate gas costs.
- `c.output` property only returns a value if the computation didn't error.
- `register_account_for_deletion` fails if an account is registered twice.
- `get_accounts_for_deletion()` returns empty if the computation errors.
- `add_log_entry` performs validation and adds the log entry.
- `get_log_entries` returns empty when computation has errored.
- `get_gas_refund` returns `0` when computation has errored.
- `get_gas_remaining` returns `0` when computation has errored.
- Use as a context manager appropriately catches and consumes VM errors raised inside of the context, resulting in an errored computation object.
- `get_gas_used` returns max gas when computation has errored.

**Comment by DavidKnott** [comment]
@pipermerriam I'm on this!
