### ISSUE TITLE
Architecture for block mining

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-evm#55]
### What is wrong?

The DAO fork rules require running some custom code prior to application of any transactions on the block in which the dao fork takes place.  Currently, this is implemented in a not-so-ideal way within the `configure_header` method.  Given the intention of the `configure_header` method, this is not the *right* place for this type of logic.

### How can it be fixed

Introduce the following workflow for block mining.

* When previous block is mined, new block is seeded (fully automated within `mine_block()`.
* New block is initialized (currenty done in `configure_header()`).  This would transition the block into the initialized state after which it cannot be reconfigured.  Probably worth renaming to `initialize_block()`.
* Transactions are applied to block.
* Block is finalized. (can be called manually to finalize a block but not mine the next one)
* Block is mined (if not already finalized, this would be automatically done)

This would introduce the following state machine `seeded > initialized > under_construction > finalized`.  This would also allow hooks to be put in place at the `initialized` and `finalized` steps which should provide cleaner ways to perform this type of logic.  My spider sense also suggests these will come in handy later.

**Comment by DavidKnott** [comment]
@pipermerriam I'd like to take a crack at this

**Comment by DavidKnott** [comment]
@pipermerriam I've been reading a lot of the VM code and it seems like `frontier` and `homestead` both fit into the same `VM.configure` API.   I'm thinking I should change not just `homestead` but the `VM` itself (starting in `evm.vm.base`).  e.g. instead of passing in: 
``` python
create_header_from_parent=staticmethod(create_homestead_header_from_parent),
````
to `VM.configure`, passing in:
``` python
initialize_block=staticmethod(homestead_initialize_block)
```
Is that what you have in mind for the new block mining workflow?

**Comment by pipermerriam** [comment]
Yes, this sounds right.  If you want to code up the initial method renaming and whatnot and have me look at it I'll be able to give you a more definitive answer as-to-whether it is going in the right direction.

**Comment by pipermerriam** [comment]
Yes, this sounds right.  If you want to code up the initial method renaming and whatnot and have me look at it I'll be able to give you a more definitive answer as-to-whether it is going in the right direction.

**Comment by pipermerriam** [comment]
no longer thinking this is the right approach.
