### ISSUE TITLE
Implement read-only wrapper for db

### ISSUE THREAD

**Issue by gsalgado** [pipermerriam/py-evm#80]
It'd be nice to have a wrapper around _BaseDB_ that allows only methods that just read from the db (e.g. _.get()_, _.exists()_), raising an error if any methods that write to the DB are called. For more info, see https://github.com/pipermerriam/py-evm/pull/76#discussion_r134647156

**Comment by egong** [comment]
https://github.com/gsalgado/py-evm/pull/2
