### ISSUE TITLE
Public key validation function

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-evm#82]
### What is wrong?

The same code for validating public keys can be found in both of these locations.

* https://github.com/pipermerriam/py-evm/blob/master/evm/utils/address.py#L30-L33
* https://github.com/pipermerriam/py-evm/blob/master/evm/utils/secp256k1.py#L22-L25

### How can it be fixed

Extract this code into a new validation function, `evm.validation.validate_raw_public_key`.  It should perform the following checks.

* the value is of type `bytes`
* the value is of length 64

**Comment by egong** [comment]
@pipermerriam giving this a go!
