### ISSUE TITLE
Passing public/private keys around in raw format is problematic

### ISSUE THREAD

**Issue by gsalgado** [pipermerriam/py-evm#93]
### What is wrong?

We currently pass pass Public/Private keys around in raw form (i.e. bytes), and in many places we have to validate them (i.e. check their type/length)

Also, the public keys we pass around do not include the '\x04' prefix (making them 64-bytes long) since they are used to generate Ethereum addresses or P2P Node IDs, and those must not include that. However, most libraries (e.g. coincurve) expect public keys to include the '\x04' prefix (with 65 bytes)

### How can it be fixed

We could have custom types for Public and Private keys to centralise validation and abstract away the differences between what we must use when generating addresses/node-ids and what the libraries expect

**Comment by pipermerriam** [comment]
@gsalgado I'm looking at writing an `ethereum-ecc` library that provides these classes.  My plan is to move the ecc backend system into that library which would get all of the ECC code out of this repository.  Part of the motivation is that we're finding we need the same primitives for some of the new feature dev in web3.py.

cc @carver

**Comment by pipermerriam** [comment]
Done in #95
